language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

install: ant deps


notifications:
  email:
    recipients:
      -juanicolombo@icloud.com
      -fran.gu1498@gmail.com
      -tkleppe@fi.uba.ar
      -nsalvanescki@fi.uba.ar
    on_failure: always
