language: java
jdk:
  - openjdk8

install: ant

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -juanicolombo@icloud.com
      -fran.gu1498@gmail.com
      -tkleppe@fi.uba.ar
      -nsalvanescki@fi.uba.ar
    on_failure: always
