language: java
jdk:
  - openjdk11
dist: trusty

script: 
- mvn test
- "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    recipients:
      -juanicolombo@icloud.com
      -fran.gu1498@gmail.com
      -tkleppe@fi.uba.ar
      -nsalvanescki@fi.uba.ar
    on_failure: always
