language: java
jdk:
  - openjdk8
dist: trusty

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
  
notifications:
  email:
    recipients:
      -juanicolombo@icloud.com
      -fran.gu1498@gmail.com
      -tkleppe@fi.uba.ar
      -nsalvanescki@fi.uba.ar
    on_failure: always
